# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Jefer
site_url: "https://www.example.com"
repo_name: Jarmos-san/jefer
repo_url: https://github.com/Jarmos-san/jefer
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - header.autohide
  icon:
    logo: material/library
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: Switch to Dark Mode
        icon: material/weather-sunny

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: Switch to Light Mode
        icon: material/weather-night

  custom_dir: overrides

extra:
  social:
    - name: Jarmos on Twitter
      icon: fontawesome/brands/twitter
      link: https://twitter.com/Jarmosan

    - name: Jarmos on LinkedIn
      icon: fontawesome/brands/linkedin
      link: https://twitter.com/Jarmosan

    - name: Jarmos on GitHub
      icon: fontawesome/brands/github
      link: https://twitter.com/Jarmosan

  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  analytics:
    provider: google
    property: G-XXXXXXXX

copyright: >
  Copyright &copy; 2016 - 2022
  <a href="https://jarmos.vercel.app" target="_blank">Somraj Saha</a>

plugins:
  - search
  # FIXME: The plugins don't install on Vercel for whatever reason, hence breaking the pipeline.
  - social:
      cards: true
      cards_dir: assets/images/social
