name: Perform Code Quality Checks

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  codeQualityCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Setup Python in the runtime.
        uses: actions/setup-python@v4.2.0

      - name: Install linters & formatters
        run: pip install black flake8 isort pydocstyle

      - name: Check for linting & formatting issues
        run: |
          isort . --check
          black . --check
          flake8 jefer tests
          pydocstyle .
