name: Perform Code Quality Checks

on:
  push:
    branches:
      - "main"

jobs:
  codeQualityCheck:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: TODO - Perform some code quality checks.
        run: echo "Hello World!"
