name: Build & Publish to PyPi

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Setup Python in the CI/CD Pipeline
        uses: actions/setup-python@v4.3.1
        with:
          python-version: "3.10"

      - name: Setup Poetry Package Manager
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"

      - name: Upload to PyPi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
