name: Run the Test Suite

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  runTests:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Setup Python in the runtime.
        uses: actions/setup-python@v4.2.0

      - name: Install Pytest
        run: pip install pytest

      - name: Run the test suite using Pytest
        run: echo "Running tests..."
